---
- hosts: docker
  sudo: yes

  vars:
    mysql_password: "my-secret-pw"

  tasks:
   - name: ensure we have wget
     apt: pkg=wget state=latest

   - name: install docker
     shell: wget -qO- https://get.docker.com/ | sh
     args:
       creates: /lib/systemd/system/docker.service

   - name: Create mysql service
     template: src=templates/mysql.service.j2 dest=/etc/systemd/system/mysql.service

   - name: Create wordpress service
     template: src=templates/wordpress.service.j2 dest=/etc/systemd/system/wordpress.service

   - name: Add mysql service
     shell: systemctl enable /etc/systemd/system/mysql.service

   - name: Add wordpress service
     shell: systemctl enable /etc/systemd/system/wordpress.service

   - name: ensure the mysql service is running
     service: name=mysql state=started enabled=yes

   - name: ensure the wordpress service is running
     service: name=wordpress state=started enabled=yes
